# Generated by Django 5.0.6 on 2026-07-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_analysed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_gaps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_recommendation',
            field=models.CharField(blank=True, choices=[('invite', 'Invite for Interview'), ('hold', 'Hold / Consider Later'), ('reject', 'Reject')], max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
