# Generated by Django 5.0.6 on 2026-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_ai_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='about',
            field=models.TextField(blank=True, default='', help_text='Short intro shown at the top of the job detail page.'),
        ),
        migrations.AlterField(
            model_name='formfieldconfig',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text / Paragraph'), ('number', 'Number'), ('select', 'Dropdown / Select'), ('yesno', 'Yes / No'), ('file', 'File Upload (single)'), ('file_multi', 'File Upload (multiple files)'), ('date', 'Date')], default='text', max_length=20),
        ),
    ]
