# Generated by Django 5.0.6 on 2026-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_add_about_to_jobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('offered', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
