# Generated by Django 5.0.6 on 2026-08-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_add_offered_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='advert',
            field=models.TextField(blank=True, default='', help_text='Short text shown on the job card listing.'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='about',
            field=models.TextField(blank=True, default='', help_text='Legacy — use advert instead.'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='PostingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='recruitment.jobposting')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
