# Generated by Django 5.0.6 on 2026-08-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_posting_advert_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_certifications',
            field=models.TextField(blank=True),
        ),
    ]
