# Generated by Django 5.0.6 on 2026-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'CDI — Permanent (Contrat à Durée Indéterminée)'), ('CDD', 'CDD — Fixed Term (Contrat à Durée Déterminée)'), ('INTERN', 'Internship Contract'), ('WACS', 'WACS Residency / Trainee Programme')], max_length=10),
        ),
    ]
