# Generated by Django 5.0.6 on 2026-03-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, default='', help_text='Official contract reference number', max_length=50),
        ),
    ]
