# Generated by Django 5.0.6 on 2026-03-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='internship_type',
            field=models.CharField(blank=True, choices=[('academic', 'Academic Internship'), ('professional', 'Professional Internship'), ('vocational', 'Vocational / Technical Internship'), ('observation', 'Observation / Discovery Internship'), ('other', 'Other')], default='', help_text='Type of internship — only applicable for INTERN contracts', max_length=20),
        ),
    ]
