# Generated by Django 5.0.6 on 2026-03-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_departmenthistory'),
        ('contracts', '0005_alter_contract_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='working_department',
            field=models.ForeignKey(blank=True, help_text='Department where the intern or resident will be working', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_placements', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='internship_type',
            field=models.CharField(blank=True, choices=[('academic', 'Academic Internship'), ('professional', 'Professional Internship'), ('pre_employment', 'Pre-Employment Internship'), ('vocational', 'Vocational / Technical Internship'), ('observation', 'Observation / Discovery Internship'), ('other', 'Other')], default='', help_text='Type of internship — only applicable for INTERN contracts', max_length=20),
        ),
    ]
