# Generated by Django 5.0.6 on 2026-04-04 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_departmenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('trimester', models.PositiveSmallIntegerField(choices=[(1, 'Trimester 1 — November to February'), (2, 'Trimester 2 — March to June'), (3, 'Trimester 3 — July to October')])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('is_distributed', models.BooleanField(default=False)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-trimester'],
                'unique_together': {('year', 'trimester')},
            },
        ),
        migrations.CreateModel(
            name='AppraisalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('employee', 'Awaiting Employee'), ('coworker', 'Awaiting Co-Worker'), ('unit_head', 'Awaiting Unit Head / Supervisor'), ('manager', 'Awaiting Line Manager'), ('hr', 'Awaiting HR'), ('director', 'Awaiting Admin Director'), ('ceo', 'Awaiting CEO'), ('done', 'Complete')], default='employee', max_length=20)),
                ('tasks_summary', models.TextField(blank=True)),
                ('tasks_assimilated', models.TextField(blank=True)),
                ('pf_quality_of_work', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('pf_quantity_of_work', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('pf_knowledge_techniques', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('pf_ability_to_learn', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('aa_motivation', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('aa_attitude_colleagues', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('aa_relations_patients', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('aa_judgment_team', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('aa_punctuality', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('aa_presentation', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('goals_to_reach', models.TextField(blank=True)),
                ('award_employee_of_month', models.BooleanField(default=False)),
                ('award_other', models.CharField(blank=True, max_length=200)),
                ('comment_on_self', models.TextField(blank=True)),
                ('comment_on_supervision', models.TextField(blank=True)),
                ('comment_on_org', models.TextField(blank=True)),
                ('employee_signed_at', models.DateTimeField(blank=True, null=True)),
                ('employee_sig_b64', models.TextField(blank=True, default='')),
                ('coworker_comment', models.TextField(blank=True)),
                ('coworker_signed_at', models.DateTimeField(blank=True, null=True)),
                ('coworker_sig_b64', models.TextField(blank=True, default='')),
                ('unit_head_comment', models.TextField(blank=True)),
                ('unit_head_signed_at', models.DateTimeField(blank=True, null=True)),
                ('unit_head_sig_b64', models.TextField(blank=True, default='')),
                ('mgr_pf_quality_of_work', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mgr_pf_quantity_of_work', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mgr_pf_knowledge_techniques', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mgr_pf_ability_to_learn', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mgr_aa_motivation', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mgr_aa_attitude_colleagues', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mgr_aa_relations_patients', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mgr_aa_judgment_team', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mgr_aa_punctuality', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('mgr_aa_presentation', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('manager_comment', models.TextField(blank=True)),
                ('manager_signed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_sig_b64', models.TextField(blank=True, default='')),
                ('hr_comment', models.TextField(blank=True)),
                ('hr_signed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_sig_b64', models.TextField(blank=True, default='')),
                ('director_comment', models.TextField(blank=True)),
                ('director_signed_at', models.DateTimeField(blank=True, null=True)),
                ('director_sig_b64', models.TextField(blank=True, default='')),
                ('ceo_comment', models.TextField(blank=True)),
                ('ceo_signed_at', models.DateTimeField(blank=True, null=True)),
                ('ceo_sig_b64', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ceo_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_appraisals', to='accounts.employee')),
                ('coworker_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coworker_appraisals', to='accounts.employee')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='appraisals.appraisalcycle')),
                ('director_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_appraisals', to='accounts.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='accounts.employee')),
                ('hr_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_appraisals', to='accounts.employee')),
                ('manager_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_appraisals', to='accounts.employee')),
                ('unit_head_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_head_appraisals', to='accounts.employee')),
            ],
            options={
                'ordering': ['employee__user__last_name', 'employee__user__first_name'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
    ]
