# Generated by Django 5.0.6 on 2026-04-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_add_score_override_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalrecord',
            name='award_bonus_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
