# Generated by Django 5.0.6 on 2026-04-29 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_departmenthistory'),
        ('appraisals', '0003_add_award_bonus_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalrecord',
            name='score_modified_at_ceo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='score_modified_at_director',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='score_modified_at_hr',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='score_modified_by_ceo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_score_mods', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='score_modified_by_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_score_mods', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='score_modified_by_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_score_mods', to='accounts.employee'),
        ),
    ]
