# Generated by Django 5.0.6 on 2026-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0004_per_role_score_modification_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalrecord',
            name='ceo_score_changes',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='director_score_changes',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='hr_score_changes',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
