# Generated by Django 5.0.6 on 2026-06-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_cycle_deadline_and_hr_unlock'),
        ('appraisals', '0005_per_role_score_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalcycle',
            name='employee_deadline',
            field=models.DateField(blank=True, help_text='Last day for employees to submit their appraisal section.', null=True),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='hr_unlock_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='hr_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='hr_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalrecord',
            name='hr_unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_appraisals', to='accounts.employee'),
        ),
    ]
