# Generated by Django 5.0.6 on 2026-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0006_add_cycle_deadline_and_hr_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalrecord',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
