# Generated by Django 5.0.6 on 2026-06-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='signatory_name',
            field=models.CharField(blank=True, default='', help_text='Full name of the person who signs contracts on behalf of the employer (e.g. CEO name).', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='signatory_title',
            field=models.CharField(blank=True, default='', help_text='Job title of the contract signatory (e.g. Chief Executive Officer).', max_length=200),
        ),
    ]
