# Generated by Django 5.0.6 on 2026-03-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Line Manager'), ('hr', 'HR Admin'), ('admin_director', 'Administration Director')], default='employee', max_length=20),
        ),
    ]
