# Generated by Django 5.0.6 on 2026-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='staff_category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('AA', 'AA'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE'), ('AF', 'AF'), ('AG', 'AG'), ('AH', 'AH'), ('AI', 'AI'), ('AJ', 'AJ'), ('AK', 'AK'), ('AL', 'AL'), ('BA', 'BA'), ('BB', 'BB'), ('BC', 'BC'), ('BD', 'BD'), ('BE', 'BE'), ('BF', 'BF'), ('BG', 'BG'), ('BH', 'BH'), ('BI', 'BI'), ('BJ', 'BJ'), ('BK', 'BK'), ('BL', 'BL')], default='', help_text='Staff classification category (A–L, AA–AL, BA–BL)', max_length=3),
        ),
    ]
