# Generated by Django 5.0.6 on 2026-03-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_staff_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Line Manager'), ('hr', 'HR Admin'), ('admin_director', 'Administration Director'), ('finance_director', 'Finance Director'), ('ceo', 'CEO')], default='employee', max_length=20),
        ),
    ]
