# Generated by Django 5.0.6 on 2026-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dismissal_date',
            field=models.DateField(blank=True, help_text='Date dismissal was issued — account deactivated after 14 days', null=True),
        ),
    ]
