# Generated by Django 5.0.6 on 2026-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employee_dismissal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.TextField(blank=True, default='', help_text='Academic and professional qualifications'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Line Manager'), ('hr', 'HR Admin'), ('admin_director', 'Administration Director'), ('finance_director', 'Finance Director'), ('ceo', 'CEO'), ('intern', 'Intern'), ('wacs_resident', 'WACS Resident / Trainee')], default='employee', max_length=20),
        ),
    ]
