# Generated by Django 5.0.6 on 2026-03-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employee_sex_nationality_contract_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_number',
            field=models.CharField(blank=True, default='', help_text='Official contract reference number', max_length=50),
        ),
    ]
