# Generated by Django 5.0.6 on 2026-03-16 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='staff_category',
            field=models.CharField(blank=True, default='', help_text='Category 1–12 with optional letter suffix (e.g. 5, 12, 12A, 12AB, 12AL)', max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid category: a number 1–12 followed by optional letters (e.g. 5, 12, 12A, 12AB, 12AL).', regex='^(?:[1-9]|1[0-2])[A-Z]{0,3}$')]),
        ),
    ]
