# Generated by Django 5.0.6 on 2026-03-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staff_category_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='school_name',
            field=models.CharField(blank=True, default='', help_text='Name of university or school (interns only)', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='speciality',
            field=models.CharField(blank=True, default='', help_text='Field of study or speciality (interns only)', max_length=200),
        ),
    ]
