# Generated by Django 5.0.6 on 2026-03-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_intern_school_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='unit_head',
            field=models.ForeignKey(blank=True, help_text='Optional Unit Head who approves before the Line Manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_head_of', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('unit_head', 'Unit Head'), ('manager', 'Line Manager'), ('hr', 'HR Admin'), ('admin_director', 'Administration Director'), ('finance_director', 'Finance Director'), ('ceo', 'CEO'), ('intern', 'Intern'), ('wacs_resident', 'WACS Resident / Trainee')], default='employee', max_length=20),
        ),
    ]
