# Generated by Django 5.0.6 on 2026-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_employee_unit_head_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.ImageField(blank=True, help_text='Scanned signature image used on official PDF forms', null=True, upload_to='signatures/'),
        ),
    ]
