# Generated by Django 5.0.6 on 2026-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_employee_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='signature',
            field=models.FileField(blank=True, help_text='Scanned signature image used on official PDF forms', null=True, upload_to='signatures/'),
        ),
    ]
