# Generated by Django 5.0.6 on 2026-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_signature_imagefield_to_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature_b64',
            field=models.TextField(blank=True, default='', help_text='Base64 PNG of signature — persists across Railway redeploys'),
        ),
    ]
