# Generated by Django 5.0.6 on 2026-03-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_signature_b64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('unit_head', 'Unit Head'), ('manager', 'Line Manager'), ('hr', 'HR Admin'), ('admin_director', 'Administration Director'), ('finance_director', 'Finance Director'), ('ceo', 'CEO'), ('intern', 'Intern'), ('wacs_resident', 'WACS Resident / Trainee'), ('super_admin', 'System Administrator')], default='employee', max_length=20),
        ),
    ]
