# Generated by Django 5.0.6 on 2026-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_departmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='staff_category',
            field=models.CharField(blank=True, default='', help_text='Staff category (any format, e.g. 5, 12B-J, A, III)', max_length=20),
        ),
    ]
