# Generated by Django 5.0.6 on 2026-06-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_employeedocument_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reports_to_director',
            field=models.BooleanField(default=False, help_text='Skip Unit Head and Line Manager steps. Leave goes directly to HR then Admin Director.'),
        ),
    ]
