# Generated by Django 5.0.6 on 2026-07-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_employee_acting_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_physician',
            field=models.BooleanField(default=False, help_text='Grants access to issue Medical Sick Leave forms (internal medicine specialist).'),
        ),
    ]
