# Generated by Django 5.0.6 on 2026-08-02 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nurse_superintendent',
            field=models.ForeignKey(blank=True, help_text='Nurse Superintendent who approves leave after Line Manager (nursing staff only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_supt_of', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='requires_nurse_supt',
            field=models.BooleanField(default=False, help_text='If checked, leave requests require Nurse Superintendent approval after Line Manager.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('unit_head', 'Unit Head'), ('manager', 'Line Manager'), ('nurse_superintendent', 'Nurse Superintendent'), ('hr', 'HR Admin'), ('generalist', 'Generalist'), ('admin_director', 'Administration Director'), ('medical_director', 'Medical Director'), ('finance_director', 'Finance Director'), ('ceo', 'CEO'), ('intern', 'Intern'), ('wacs_resident', 'WACS Resident / Trainee'), ('super_admin', 'System Administrator')], default='employee', max_length=20),
        ),
    ]
