# Generated by Django 5.0.6 on 2026-03-12 15:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_employee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('verbal_warning', 'Verbal Warning'), ('written_caution', 'Written Caution'), ('final_warning', 'Final Written Warning'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal')], max_length=20)),
                ('date_issued', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='discipline_docs/')),
                ('suspension_start', models.DateField(blank=True, null=True)),
                ('suspension_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='accounts.employee')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_disciplines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_issued', '-created_at'],
            },
        ),
    ]
