# Generated by Django 5.0.6 on 2026-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinerecord',
            name='recommendation_note',
            field=models.TextField(blank=True, default='', help_text="Manager's recommendation details (not visible to employee)"),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='recommended_sanction',
            field=models.CharField(blank=True, choices=[('', '— No recommendation —'), ('written_caution', 'Written Caution'), ('final_warning', 'Final Written Warning'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal'), ('no_further_action', 'No Further Action Required')], default='', help_text='Proposed follow-up action recommended by the issuing manager (not visible to employee)', max_length=20),
        ),
    ]
