# Generated by Django 5.0.6 on 2026-03-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_disciplinerecord_recommendation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinerecord',
            name='director_proposed_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='director_proposed_sanction',
            field=models.CharField(blank=True, choices=[('', '— No recommendation —'), ('written_caution', 'Written Caution'), ('final_warning', 'Final Written Warning'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal'), ('no_further_action', 'No Further Action Required')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='hr_proposed_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='hr_proposed_sanction',
            field=models.CharField(blank=True, choices=[('', '— No recommendation —'), ('written_caution', 'Written Caution'), ('final_warning', 'Final Written Warning'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal'), ('no_further_action', 'No Further Action Required')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='disciplinerecord',
            name='recommendation_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
