# Generated by Django 5.0.6 on 2026-05-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_disciplinerecord_director_proposed_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinerecord',
            name='is_proposal',
            field=models.BooleanField(default=False, help_text='Awaiting formal HR execution; not yet visible to the employee as a notice'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='proposal_note',
            field=models.TextField(blank=True, default='', help_text='Additional context submitted with the proposal'),
        ),
    ]
