# Generated by Django 5.0.6 on 2026-03-10 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_role'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='director_action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_actions', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='director_action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='director_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Manager Approval'), ('manager_approved', 'Pending HR Approval'), ('hr_approved', 'Pending Director Approval'), ('approved', 'Approved'), ('rejected_manager', 'Rejected by Manager'), ('rejected_hr', 'Rejected by HR'), ('rejected_director', 'Rejected by Director'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
