# Generated by Django 5.0.6 on 2026-03-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_director_action_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_deductible',
            field=models.BooleanField(default=True, help_text='If checked, approved days are subtracted from annual leave balance.'),
        ),
    ]
