# Generated by Django 5.0.6 on 2026-03-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_employee_unit_head_alter_employee_role'),
        ('leaves', '0005_leavebalance_carried_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='backup_employee',
            field=models.ForeignKey(blank=True, help_text='Colleague covering during this leave.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_leaves', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='unit_head_action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_head_actions', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='unit_head_action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='unit_head_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('unit_head_approved', 'Pending Manager Approval'), ('manager_approved', 'Pending HR Approval'), ('hr_approved', 'Pending Director Approval'), ('approved', 'Approved'), ('rejected_unit_head', 'Rejected by Unit Head'), ('rejected_manager', 'Rejected by Manager'), ('rejected_hr', 'Rejected by HR'), ('rejected_director', 'Rejected by Director'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
