# Generated by Django 5.0.6 on 2026-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_leaverequest_backup_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='director_sig_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_sig_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hr_sig_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_sig_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='unit_head_sig_b64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
