# Generated by Django 5.0.6 on 2026-08-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_nurse_superintendent_role'),
        ('leaves', '0009_leave_reversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='nurse_supt_action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_supt_actions', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='nurse_supt_action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='nurse_supt_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='nurse_supt_sig_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('unit_head_approved', 'Pending Manager Approval'), ('manager_approved', 'Pending Nurse Superintendent / HR Approval'), ('nurse_supt_approved', 'Pending HR Approval'), ('hr_approved', 'Pending Director Approval'), ('approved', 'Approved'), ('rejected_unit_head', 'Rejected by Unit Head'), ('rejected_manager', 'Rejected by Manager'), ('rejected_nurse_supt', 'Rejected by Nurse Superintendent'), ('rejected_hr', 'Rejected by HR'), ('rejected_director', 'Rejected by Director'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
