# Generated by Django 6.0.8 on 2026-10-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_tentative_leave_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_advance',
            field=models.BooleanField(default=False, help_text="Leave approved against next year's entitlement (balance was exhausted)."),
        ),
    ]
