# Generated by Django 5.0.6 on 2026-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_simplify_payslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='payslip_file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/%Y/'),
        ),
    ]
