# Generated by Django 5.0.6 on 2026-08-06 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0030_nurse_superintendent_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_type', models.CharField(choices=[('resignation', 'Resignation'), ('retirement', 'Retirement'), ('termination', 'Termination'), ('transfer', 'Transfer'), ('contract_end', 'Contract End')], max_length=20)),
                ('exit_date', models.DateField(help_text='Last working day')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Clearance'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='HR internal notes')),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_feedback', models.TextField(blank=True)),
                ('interview_done', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='accounts.employee')),
                ('initiated_by', models.ForeignKey(help_text='HR/manager who opened this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exits_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('owner', models.CharField(choices=[('hr', 'HR Department'), ('it', 'IT Department'), ('finance', 'Finance'), ('manager', 'Line Manager'), ('employee', 'Employee'), ('security', 'Security')], default='hr', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_tasks_done', to=settings.AUTH_USER_MODEL)),
                ('exit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='offboarding.exitrequest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
