# Generated by Django 5.0.6 on 2026-07-06 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0028_employee_is_physician'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issuance', models.DateField(default=django.utils.timezone.localdate)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Optional medical notes (internal use only, not printed).')),
                ('status', models.CharField(choices=[('pending_line_manager', 'Pending Line Manager Endorsement'), ('pending_hr', 'Pending HR Endorsement'), ('approved', 'Fully Endorsed'), ('rejected_line_manager', 'Rejected by Line Manager'), ('rejected_hr', 'Rejected by HR')], default='pending_line_manager', max_length=30)),
                ('line_manager_action_date', models.DateTimeField(blank=True, null=True)),
                ('line_manager_remarks', models.TextField(blank=True)),
                ('hr_action_date', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_sick_leaves', to='accounts.employee', verbose_name='Patient / Employee')),
                ('hr_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_leave_hr_actions', to='accounts.employee')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_sick_leaves_issued', to='accounts.employee', verbose_name='Issuing Physician')),
                ('line_manager_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_leave_lm_actions', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Medical Sick Leave',
                'verbose_name_plural': 'Medical Sick Leaves',
                'ordering': ['-date_of_issuance', '-created_at'],
            },
        ),
    ]
