# Generated by Django 5.0.6 on 2026-07-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsickleave',
            name='hr_sig_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicalsickleave',
            name='issued_sig_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicalsickleave',
            name='lm_sig_b64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
