# Generated by Django 6.0.8 on 2026-10-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_nurse_superintendent_role'),
        ('medical_leave', '0002_add_signature_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsickleave',
            name='director_action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_leave_director_actions', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='medicalsickleave',
            name='director_action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalsickleave',
            name='director_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalsickleave',
            name='director_sig_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='medicalsickleave',
            name='status',
            field=models.CharField(choices=[('pending_line_manager', 'Pending Line Manager Endorsement'), ('pending_hr', 'Pending HR Endorsement'), ('pending_director', 'Pending Admin Director Acceptance'), ('approved', 'Fully Endorsed'), ('rejected_line_manager', 'Rejected by Line Manager'), ('rejected_hr', 'Rejected by HR'), ('rejected_director', 'Rejected by Admin Director')], default='pending_line_manager', max_length=30),
        ),
    ]
