# Generated by Django 6.0.8 on 2026-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_leave', '0003_add_director_step_to_sick_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalsickleave',
            name='director_action_by',
        ),
        migrations.RemoveField(
            model_name='medicalsickleave',
            name='director_action_date',
        ),
        migrations.RemoveField(
            model_name='medicalsickleave',
            name='director_remarks',
        ),
        migrations.RemoveField(
            model_name='medicalsickleave',
            name='director_sig_b64',
        ),
        migrations.AlterField(
            model_name='medicalsickleave',
            name='status',
            field=models.CharField(choices=[('pending_line_manager', 'Pending Line Manager Endorsement'), ('pending_hr', 'Pending HR Endorsement'), ('approved', 'Fully Endorsed'), ('rejected_line_manager', 'Rejected by Line Manager'), ('rejected_hr', 'Rejected by HR')], default='pending_line_manager', max_length=30),
        ),
    ]
