# Generated by Django 5.0.6 on 2026-03-16 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('leave_submitted', 'Leave Submitted'), ('leave_manager_approved', 'Leave Manager Approved'), ('leave_hr_approved', 'Leave HR Approved'), ('leave_approved', 'Leave Fully Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled'), ('discipline', 'Discipline Notice'), ('contract_issued', 'Contract Issued'), ('contract_renewed', 'Contract Renewed'), ('contract_terminated', 'Contract Terminated'), ('account_activated', 'Account Activated'), ('system', 'System')], default='system', max_length=30)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
