# Generated by Django 5.0.6 on 2026-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_contract_expiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leave_submitted', 'Leave Submitted'), ('leave_manager_approved', 'Leave Manager Approved'), ('leave_hr_approved', 'Leave HR Approved'), ('leave_approved', 'Leave Fully Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled'), ('discipline', 'Discipline Notice'), ('contract_issued', 'Contract Issued'), ('contract_renewed', 'Contract Renewed'), ('contract_terminated', 'Contract Terminated'), ('account_activated', 'Account Activated'), ('contract_expiry', 'Contract Expiry Alert'), ('birthday', 'Birthday Greeting'), ('appraisal_warning', 'Appraisal Warning'), ('appraisal', 'Appraisal'), ('payslip', 'Payslip Available'), ('reminder', 'Pending Action Reminder'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
